### ISSUE TITLE
Drawing fails on Google Colab

### ISSUE THREAD

**Issue by timcash** [pygae/pyganja#52]
I used the follow in Google colab notebook
```
!pip install clifford
!pip install pyganja
```
```
from clifford.tools.g3c import random_line
from pyganja import *

draw([random_line() for i in range(10)])
```
And I get the follow error
```
/usr/local/lib/python3.6/dist-packages/pyganja/__init__.py:2: UserWarning: Failed to import cef_gui, cef functions will be unavailable
  from .script_api import *
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-a7564f120d39> in <module>()
      2 from pyganja import *
      3 
----> 4 draw([random_line() for i in range(10)])

3 frames
/usr/local/lib/python3.6/dist-packages/pyganja/script_api.py in _to_scene_string(objects)
    256     if isinstance(objects, list):
    257         sc = GanjaScene()
--> 258         sc.add_objects(objects, color=color, static=static)
    259         return str(sc)
    260     elif isinstance(objects, str):

NameError: name 'color' is not defined
```

**Comment by hugohadfield** [comment]
Ah yes, this was fixed in this [commit](https://github.com/pygae/pyganja/commit/7ea791d0b2d903202d9667c50964f787854f512d) but looks like we haven't done a release in a while. We will do one very shortly, in the meantime install from master will be a work around for this bug, try changing that line to:
```
!pip install git+https://github.com/pygae/pyganja.git
```
On google collab however I am still not getting any output although there is no error, I've started looking into that but I suspect it may be to do with outputting javascript into collab which, like jupyter lab, it probably won't like

**Comment by hugohadfield** [comment]
Changing the test to:
```
!pip install git+https://github.com/pygae/pyganja.git
!pip install clifford

from clifford.tools.g3c import random_line, layout
from pyganja import *

gs = GanjaScene()
js = generate_notebook_js(gs, sig=layout.sig)
print(js)

import IPython
display(js)

print('Cell complete')
```
reproduces the javascript error failure to draw. The cell executes and prints cell complete with no error messages but also no output. In the development console however we get the following error:
![image](https://user-images.githubusercontent.com/3056964/97238499-78669000-17e1-11eb-9040-8625a42b5382.png)

**Comment by hugohadfield** [comment]
Adding the line:
```
display(IPython.core.display.HTML('''<script src="/static/components/requirejs/require.js"></script>'''))
```
gets rid of the requirejs error but still no output visible in colab

**Comment by hugohadfield** [comment]
@timcash I have just triggered a release so the version in pypi should now be equal with master https://pypi.org/project/pyganja/0.0.13/

**Comment by timcash** [comment]
Wonderful

**Comment by jmizaret** [comment]
I am facing the same problem: installed node.js and pyganja v0.015 on mac. Clifford working well.
UserWarning: Failed to import cef_gui, cef functions will be unavailable from .script_api import *

running the code below:

from clifford.tools.g3c import *
from pyganja import *

object_array = [
random_conformal_point(),
random_point_pair(),
random_circle(),
random_line(),
random_sphere(),
random_plane()
]

# The simplest way to use pyganja
draw(object_array,
     static=False ,
     scale=0.1)
